### ISSUE TITLE
Failure: buf.build/googleapis/googleapis:8f04c867ddf14e13a231d5119b8ebb8b: does not exist

### ISSUE THREAD

**Issue by acrazing** [bufbuild/buf#1409] opened 2022-09-16 03:13 UTC
It seems that `buf.build/googleapis/googleapis` was recreated and `buf.build/envoyproxy/protoc-gen-validate` depended on an old version.

This is my `buf.lock` file content:

```yaml
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: envoyproxy
    repository: protoc-gen-validate
    commit: 45685e052c7e406b9fbd441fc7a568a5
  - remote: buf.build
    owner: googleapis
    repository: googleapis
    commit: 8d7204855ec14631a499bd7393ce1970
```

**Comment by friedemannf** [comment] 2022-09-16 10:30
We're noticing the same problem, pipelines are failing.
Did you come up with any workaround so far?

**Comment by robbertvanginkel** [comment] 2022-09-16 13:25
I'm going to close this as a duplicate of https://github.com/bufbuild/buf/issues/1380, please see that thread for the background on why the module was deleted and how to resolve (updating to the latest version using `buf mod update` should get you in a working state again).

**Closed by robbertvanginkel** 2022-09-16 13:25 UTC
