### ISSUE TITLE
inputs paths non base directory

### ISSUE THREAD

**Issue by dxinli** [bufbuild/buf#3242] opened 2024-08-16 01:55 UTC
### GitHub Repository

https://github.com/dxinli/why-buf.git

### What's up?

buf.yaml:
version: v2
modules:
  - path: api
  - path: third_party

buf.errors.gen.yaml
inputs:
  - directory: api
    paths:
      - helloworld/v1/error_reason.proto

this paths inputs is not api/helloworld/v1/error_reason.proto ? , but buf generate report no .proto files are found in your input

**Comment by bufdev** [comment] 2024-08-16 03:17
The repository you provided is not viewable. Please provide a reproducible example with a public repository demonstrating your issue and we will be happy to take a look. Closing this issue until this is provided.

**Closed by bufdev** 2024-08-16 03:17 UTC

**Comment by dxinli** [comment] 2024-08-16 06:17
i make the repository is public

**Comment by bufdev** [comment] 2024-08-16 10:44
Please provide reproduction steps, what you saw, and what you expected to see. The bug issue template has instructions on what to do (you used the other template). Without exact reproduction steps, we can't assist you here.

**Comment by dxinli** [comment] 2024-08-19 12:16
ok, thanks ,i will report new issue with bug template

**Comment by doriable** [comment] 2024-08-21 16:18
This is a duplicate of https://github.com/bufbuild/buf/issues/3252
