### ISSUE TITLE
bug report: error when two files with same name exist

### ISSUE THREAD

**Issue by tshradheya** [bufbuild/buf#2062] opened 2023-05-09 08:44 UTC
I have a project with two files of same name under different directory

`x/abc.proto` and `y/abc.proto`

When i run `buf lint` or `buf breaking` it errors out with success exit code

```
Failure: failed to enumerate module files: abc.proto exists in multiple locations: x/abc.proto y/abc.proto
```

This usually works fine as I have other proto files, but could it be cause these files contain service and hence erroring out?

Code ref: https://github.com/bufbuild/buf/blob/main/private/bufpkg/bufmodule/module.go#L271
This is the code ref i found that may be causing it but I am not sure how to fix it exactly in a clean way

Also is there any workaround for this?

**Comment by bufdev** [comment] 2023-05-12 15:36
Closing for now - let us know if you have any updates here! I believe this is working as intended though.

**Closed by bufdev** 2023-05-12 15:36 UTC

**Comment by tshradheya** [comment] 2023-05-12 18:02
@bufdev yes, what you said makes sense. maybe it will be nice if command fails with failure exit code instead of success cause now it was silently failing with this error

**Comment by robertcnix** [comment] 2023-06-20 20:27
@bufdev Can you clarify why this file-name restriction exists? I would expect that having a module, `x/buf.yaml` and `y/buf.yaml`, would allow me to have files named the same in those two modules. The types in `x` and `y` are different so why should there be a global namespace for modules in a workspace? The workspace is about being able to share across modules. I can understand that if `x` needs to import from `y`, then _maybe_ this restriction will matter. But what if `x` and `y` both only import from `z` but `x` and `y` are happen to have a file with the same name. So what. They're different because they're different modules. 

Please help me understand as I have this `x,y,z` scenario and it doesn't seem like buf has a solution for it. Naming my `.proto` files differently isn't ideal. We put a message per file and we have overlapping messages named the same in different modules but they are indeed different messages (they different fields) due to specifics of each module.

**Comment by bufdev** [comment] 2023-06-20 21:30
It's not just that Buf doesn't have a solution for it, it's that no one does at the moment - file path uniqueness (and type uniqueness) is a core property of the Protobuf language. See https://buf.build/docs/build/usage/#2.1.-workspace-requirements for a more thorough discussion on the topic.

Protobuf as a language does not consider them to be different files or types if they are in different modules - you import based on file path in Protobuf. We've considered designs to make `buf` handle fully-qualified imports, ie `import "buf.build/acme/foo/bar.proto";`, but this is a tougher problem than you may think, and would cause some unsolved downstream issues across the ecosystem of existing Protobuf plugins that there aren't clear solutions for.
