### ISSUE TITLE
feedback: Protobuf formatting

### ISSUE THREAD

**Issue by slimsag** [bufbuild/buf#178] opened 2020-11-02 16:47 UTC
https://docs.buf.build/lint-checkers#formatting outlines why `buf` today doesn't support formatting (mentioning to flag that I have seen/read this)

I think these points are all valid, especially the third point about parsers - however I would argue this makes `buf` not a complete replacement for `prototool`: there is a lot of demand these days for unified language formatting (cargo-fmt in Rust, `go fmt`, `zig fmt`, `clang-format`, etc.) and I think `buf` would be the right place for offering this - even if it is optional, mentions there are cases where it doesn't work, and even not recommended by default.

If `buf` doesn't provide it, I think people will reach for [`prototool format`](https://github.com/uber/prototool#prototool-format) (I personally will) and, longer-term, push for a different protobuf formatter - I think `buf` would be in the unique position of offering a complete, holistic, unified experience for working with Protobuf though.

Totally understand this is not on immediate roadmap / goal, but curious to hear about long-term direction here and if something like a PR for `buf fmt` as a direct copy of what `prototool format` today does would be welcomed or not.

**Comment by bufdev** [comment] 2020-11-02 16:49
Buf's goal is not meant to be a prototool replacement. Formatting is hard - there's lots of attempts out there, but no one does it correctly, as that document outlines. This is on our roadmap, but not a high priority. We'll get to it when we can. Duplicate of #11.

**Closed by bufdev** 2020-11-02 16:49 UTC
Labels: Duplicate

**Comment by bufdev** [comment] 2020-11-02 16:51
Additionally, copying `prototool format` into buf is not OK for the reasons outlined in that document - `prototool format` is incorrect, and will result in corrupted Protobuf files if used extensively enough. `prototool format` uses a parser that parses invalid Protobuf, and does not parse all Protobuf correctly. I know because I wrote it, and wish I had not :-)

**Comment by slimsag** [comment] 2020-11-02 16:54
Thanks for the link, sorry for the duplicate issue!

I didn't realize `prototool format` also suffered from these issues, what you said above is very insightful for me, thank you!

**Comment by bufdev** [comment] 2021-01-24 15:07
Just an update: we are working on this, although not high priority, but we should have something out in the future.
