### ISSUE TITLE
`option go_package` changes aren't pushed

### ISSUE THREAD

**Issue by TonyPapousekLC** [bufbuild/buf#1320] opened 2022-08-05 18:53 UTC
To reproduce:
* Change the `option go_package` string within a `.proto` file (without modifying the definitions)
* Run buf push with a custom tag

The tag will update on the BSR, but the files will not change. The old version of the proto files will remain, making it out of sync w/ the source code.

**Comment by amckinney** [comment] 2022-08-11 16:07
Hey @TonyPapousekLC, I wasn't able to reproduce this. I added a `go_package` option to my `.proto` file,` pushed the content, then edited my `go_package` option` and successfully pushed again and received a new commit. If I push the same module without editing the content, then the server informs me that the content hasn't changed (as expected).

If your `.proto` input isn't private/sensitive, could you share it so that I can try to reproduce? Otherwise, there might have been something else going on in your setup.

I'll close this for now since things appear to be working, but please feel free to reopen if you continue to see issues on your end.

**Closed by amckinney** 2022-08-11 16:07 UTC
Labels: Needs Investigation
