### ISSUE TITLE
Forbidden docs.buf.build from Russia

### ISSUE THREAD

**Issue by nikitaksv** [bufbuild/buf#2030] opened 2023-04-27 14:47 UTC
Hello, colleagues!
I recently noticed that the buf build documentation page was banned for Russia (even via VPN). Please remove the BSR and docs block. The tool is used by many open source contributors from Russia, including me. It is a pity that now it is impossible to use the tool at full capacity and help the community. I hope for understanding!

**Comment by bufdev** [comment] 2023-04-27 17:33
Duplicate of https://github.com/bufbuild/buf/issues/1005

**Closed by bufdev** 2023-04-27 17:33 UTC
