### ISSUE TITLE
Buf Commands Run Slowly In Monorepo

### ISSUE THREAD

**Issue by edzaffirm** [bufbuild/buf#2345] opened 2023-08-03 23:09 UTC
Hi,

I'm trying to add `buf` to a large monorepo, with a `buf.yaml` file placed in the root of our VCS. When I run `buf lint --path a/b/foo.proto --path a/b/bar.proto`, it can take up to 40 seconds to resolve, while using the protoc plugin to to build _and_ lint those same proto files resolves in about a second.

Similarly, I tried using the editor extensions to auto-format my `.proto` files on save, which takes about 40 seconds as well. However, if I do it via `buf format` in the directory of those proto files, it formats almost instantaneously.

Is there anything we can do here to reduce the performance differences? I'd really like to be able to leverage the CLI and editor integrations more.

**Comment by timostamm** [comment] 2023-08-04 07:45
Hey Ed, can you confirm that this happens with the latest release v1.25.1? The release includes a fix for what seems to be the issue you are running into. See https://github.com/bufbuild/buf/issues/2333 and the fix https://github.com/bufbuild/buf/pull/2337.

**Comment by bufdev** [comment] 2023-08-04 16:54
This seems like a duplicate of #2333, which was fixed in v1.25.1. Let us know if not, thanks.

**Closed** 2023-08-04 16:55 UTC

**Comment by edzaffirm** [comment] 2023-08-04 20:38
Thanks for the follow up! A few things:

- 1.25.1 definitely helped with `buf lint`! Unfortunately, formatting is still super slow via the VS Code buf extension.
- To upgrade to buf 1.25.1, I had to do `brew install buf` --> whereas `brew install bufbuild/buf/buf` (which is the documented way to install buf via Homebrew) is still a no-op.

**Comment by mboulton-fathom** [comment] 2023-09-06 11:31
Can also confirm that this is still an issue, even in very small cases. Running against a folder with 1 proto file in it:
```
$ buf format -w --path path/to/proto/ --debug
DEBUG   get_source_or_module_ref        {"duration": "20.345µs"}
DEBUG   get_config      {"duration": "208.484µs"}
DEBUG   get_config      {"duration": "138.492µs"}
DEBUG   get_module_config       {"duration": "604.103µs"}
DEBUG   command {"duration": "1.724483386s"}
```
Running against that one file:
```
$ buf format -w --path path/to/proto/file.proto --debug
DEBUG   get_source_or_module_ref        {"duration": "23.137µs"}
DEBUG   get_config      {"duration": "384.971µs"}
DEBUG   get_config      {"duration": "1.163826ms"}
DEBUG   get_module_config       {"duration": "2.025039ms"}
DEBUG   command {"duration": "10.366107ms"}
```
