### ISSUE TITLE
Respect `ignore_unstable_packages` with FILE level breaking changes.

### ISSUE THREAD

**Issue by jon-whit** [bufbuild/buf#325] opened 2021-05-21 21:52 UTC
Suppose I have a project structured like this at some specific commit in time:

```
my-project/
  protos/mypackage/v1alpha1/stub.proto
  buf.yaml
```

and a `buf.yaml` like this:
```yaml
version: v1beta1
build:
  roots:
    - protos
breaking:
  ignore_unstable_packages: true
```
----

If I rename the proto package at some later time (because I'm actively iterating on the definitions), for example:
```
my-project/
  protos/newpackage/v1alpha1/stub.proto
  buf.yaml
```

When I run a breaking change check, I get an error:
```bash
buf breaking --against "https://github.com/my-project#branch=master"
<input>:1:1:Previously present file "mypackage/v1alpha1/stub.proto" was deleted.
```

If `ignore_unstable_packages` is enabled, I would expect the change from the package `mypackage/v1alpha1` to `newpackage/v1alpha1` to not cause an error.

From a client perspective this is technically a deletion of `mypackage/v1alpha1` and a new introduction of package `newpackage/v1alpha1`. But I guess I'd expect `ignore_unstable_packages` to ignore the fact that `mypackage/v1alpha1` was deleted because it is a `v1alpha1` package.

How can I achieve this workflow without breaking my builds with `buf breaking ...`?

**Comment by jon-whit** [comment] 2021-05-21 22:12
This also relates to #37

**Comment by AlexeiZenin** [comment] 2021-05-25 20:25
You could add a filter step in your pipelines to ignore output from `buf breaking` for these specific unstable packages and thus not fail your builds. Ideally you are correct that if that option exists it should apply correctly.

**Comment by jon-whit** [comment] 2021-05-26 14:56
@AlexeiZenin agreed, but the whole point of the flag is to ignore any package that is unstable in the first place, regardless of if it has been deleted or not. So I'd definitely like to see a fix for this.

**Comment by jon-whit** [comment] 2021-06-27 22:10
Maintainers? Anyone planning on resolving this?

**Comment by bufdev** [comment] 2021-06-28 14:18
While I understand the confusion, what you're asking for isn't really possible as part of the current paradigm.

`buf` considers locations and ignores based on your *current* Protobuf definitions (in `.`), not your *against* Protobuf definitions (in `https://github.com/my-project#branch=master`). In the above case, your current Protobuf definitions do not have this file. Since ignores (such as `ignore_unstable_packages`) are processed based on your current set of Protobuf definitions, and this set does not have any file to check for an unstable package to ignore, `ignore_unstable_packages` can't ignore this file.

I'm inclined to close this as working as intended, but will leave open briefly for comment.

**Comment by jon-whit** [comment] 2021-06-28 14:48
@bufdev regardless of the contents of the current working branch as compared to the local changes, if I have chosen to `ignore_unstable_packages` then `buf` should do exactly that. If a package has a version that indicates it is unstable, it should be ignored period. This could easily be achieved by ignoring the fact that the local changes no longer have the same protobuf definitions in the current working branch. The check would look something like this:

1. Mark all stable packages defined in `https://github.com/my-project#branch=master` (call this set A)
2. Mark all stable packages defined in the current local working directory (call this set B).
3. Take the set intersection of A & B. If there is a difference, then `buf` would return an error. Otherwise it should be fine, because the assumption is that the packages were marked as unstable and can be deleted as such..

Could you help me understand why this is currently intended behavior? It is quite confusing as a dev experience, which is why I'm reporting it.

**Comment by bufdev** [comment] 2021-06-28 15:49
I can see the argument - similar to https://github.com/bufbuild/buf/issues/37#issuecomment-598338942, the current implementation is "correct", which we strive for, even if a little confusing for this case. The correct behavior is to respect ignores against your current files, as the config only relates to current files, not previous files.

However, it's worth exploring if we want to expand the defintion of ignore. We'll do so and report back.

**Comment by bufdev** [comment] 2021-06-28 21:57
@jon-whit can you try https://github.com/bufbuild/buf/pull/349 and see if it fixes your problem? `go get github.com/bufbuild/buf/cmd/buf@extra-ignore-descriptors` will install the binary from this branch at `$GOBIN` or `$GOPATH/bin`.

**Closed** 2021-06-28 22:23 UTC

**Comment by bufdev** [comment] 2021-06-28 22:25
I believe this is fixed on master, you can test it out with `go get github.com/bufbuild/buf/cmd/buf@master`. This will go out in the next release.

**Comment by jon-whit** [comment] 2021-07-08 22:21
@bufdev has this been released yet?

**Comment by bufdev** [comment] 2021-07-09 14:30
Yes
