### ISSUE TITLE
Add support for name filtering in `buf generate` command

### ISSUE THREAD

**Issue by remyleone** [bufbuild/buf#854] opened 2022-01-14 15:04 UTC
If I have multiple generators defined in my `buf.gen.yaml`, sometimes I want only to launch a subset of the generators. Could it be possible for the `buf generate` command to accept a `name` option/filter that will only select a subset of the generators defined in the config file or pass through the template option?

**Comment by robbertvanginkel** [comment] 2022-01-14 15:29
We currently treat `buf.gen.yaml` as all or nothing in terms of running all defined codegenerators, similar to how templates are defined and work with remote generation on the BSR. 

If you want to be able to run different sets of generators, we currently recommend that you keep multiple `buf.subset.gen.yaml` files and use the `--template` flag when doing `buf generate`. Note that the `--template` doesn't only take files but can also take a json encoded template from the commandline. Is that a solution that would work for you?

**Comment by remyleone** [comment] 2022-01-14 16:17
That would mean duplicating configuration for all generators in all the subsets files :/ the number of files to keep on disk will keep growing with this solution. Filtering seems to be more elegant.

**Comment by amckinney** [comment] 2022-01-14 18:03
I want to challenge this a bit. I'm not sure that you'd need to duplicate anything across any files - you just need to write your files granularly so that they can composed together by separate `buf generate` invocations. I think the number of files you'd need is equivalent to the number of `buf generate --name` invocations you'd need to write if we supported a `--name` filter, right?

Regardless, a `--name` filter is a reasonable request - we can consider it, but we have taken a strict stance that input configuration goes in flags, template configuration goes in `buf.gen.yaml`, and this would make that split murkier.

I also worry about the implication on other features in the `buf.gen.yaml` like [Managed Mode](https://docs.buf.build/generate/managed-mode). If we have a way to select individual `plugins`, would we also need a way to enable/disable different parts of the `managed` key? This could quickly get unwieldy if so.

**Comment by anandwana001** [comment] 2022-01-20 05:02
> We currently treat `buf.gen.yaml` as all or nothing in terms of running all defined codegenerators, similar to how templates are defined and work with remote generation on the BSR.
> 
> If you want to be able to run different sets of generators, we currently recommend that you keep multiple `buf.subset.gen.yaml` files and use the `--template` flag when doing `buf generate`. Note that the `--template` doesn't only take files but can also take a json encoded template from the commandline. Is that a solution that would work for you?

@robbertvanginkel How to keep multiple `buf.subset.gen.yaml` files? It rises the duplicate name issue in project.

**Comment by bufdev** [comment] 2022-01-20 14:53
Here's how we maintain multiple sets: https://github.com/bufbuild/buf/tree/main/data/template

You can use the `--template` flag https://github.com/bufbuild/buf/blob/main/make/buf/all.mk#L104

**Comment by bufdev** [comment] 2022-02-17 00:13
We're going to reconsider this

**Comment by AndreasBergmeier6176** [comment] 2023-10-26 11:32
Our use case would be to filter the files that get considered in a plugin `entry`.
E.g. when we have `foo.proto` and `bar.proto` it would be great to be able to directly specify, which protos will be used for the plugin invocation.

Basically a mechanism which loads the `path` option from `buf.gen.yaml`.

**Comment by doriable** [comment] 2024-06-10 20:56
Closing this issue as a duplicate of #3060 to consolidate discussion on supporting plugin configurations on a per module/input basis.

**Closed by doriable** 2024-06-10 20:56 UTC
Labels: Feature, Wishlist
