### ISSUE TITLE
latest docker version buf formats text into invalid protobuf

### ISSUE THREAD

**Issue by vincenthouyi** [bufbuild/buf#1370] opened 2022-08-31 06:48 UTC
The `latest` docker version buf will format text with escaped quote and line break into invalid protobuf file.

Here is a minimal sample to reproduce the issue:

original protobuf:
```protobuf
syntax = "proto3";

package bug.report.v1;

import "protoc-gen-openapiv2/options/annotations.proto";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  info: {
    description: "This is \"title\"\nThis is second line \"aaaaa\"";
  };
};
```
After running `docker run -v $(PWD):/home/ubuntu/ -w /home/ubuntu bufbuild/buf:latest format -w`, the resulting protobuf is:
```protobuf
syntax = "proto3";

package bug.report.v1;

import "protoc-gen-openapiv2/options/annotations.proto";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  info: {
    description: 'This is "title"
This is second line "aaaaa"';
  };
};
```
This issue is not seen on `1.7.0` version.

I'm not sure what is the real version of this `latest` docker container. It is only tagged as `latest`, and having different hash with `1.7.0` container. This is the link to the docker hub of this release: [link](https://hub.docker.com/layers/buf/bufbuild/buf/latest/images/sha256-e904205fb7b99dd4ed65d0a3243b36aefffbe9b6223a7608a26671e4914f4996?context=explore)

**Comment by amckinney** [comment] 2022-08-31 16:24
Thanks for the issue @vincenthouyi, it looks like this regression was introduced in https://github.com/bufbuild/buf/commit/5c3a10cbe3546c79baea42e7c498de3e01e36324, but it has not yet been released with a semantic version tag (i.e. `v1.8.0`). You're able to notice the problem because you're using `latest`.

In short, the newline literal `\n` is being transformed when we attempt to wrap the string value with single quotes instead of double quotes, which is clearly invalid.

We'll try to get a fix out soon!

**Closed** 2022-09-01 21:01 UTC
Labels: Bug
