### ISSUE TITLE
Docker use for protoc stubs generation

### ISSUE THREAD

**Issue by carloslimasis** [bufbuild/buf#228] opened 2021-01-02 13:22 UTC
Hi!

I'm trying to generate my stubs with the docker image but I received this error 

```
plugin go: could not find protoc plugin for name go
```

```
docker run \
	--volume "$(shell pwd):/workspace" \
	--workdir /workspace \
	bufbuild/buf generate --template buf.gen.yaml api/proto
```

when I use the buf directly on my machine I need to get some dependencies, for example:

```
go get -u google.golang.org/grpc
go get -u github.com/golang/protobuf/protoc-gen-go
```

then after this, works fine

What's the better approach to use the buf with docker?
What's I can do in this case that I have a protoc plugin error?

**Comment by bufdev** [comment] 2021-01-02 14:53
Duplicate of https://github.com/bufbuild/buf/issues/184. You need to build your own Docker image to use your own plugins.

**Closed by bufdev** 2021-01-02 14:53 UTC

**Comment by bliuchak** [comment] 2021-02-09 07:46
I came here with exactly same problem :) Just in case sharing my [workaround](https://gist.github.com/bliuchak/233ec886374db630cd6a7327d82ff0f6).
