### ISSUE TITLE
buf generate fails when path to proto file starts with @

### ISSUE THREAD

**Issue by predmond** [bufbuild/buf#428] opened 2021-08-17 19:31 UTC
The project I am trying to build has a structure like:

```
generated/proto/@foo/bar.proto
generated/proto/@foo/baz.proto
```
and my `buf.yaml` has
```
build:
  roots:
    - generated/proto
```

when I run `buf generate` I get errors like:
```
Failed to open argument file: foo/bar.proto
Failed to open argument file: foo/baz.proto
```

So clearly it is treating @ as a path to an argument file.

Unless the argument file is explicitly passed to the command line (e.g., `buf generate @args`) I don't think it should treat @ as an argument file.

(`buf lint` and `buf ls-files` don't have this issue)

**Comment by doriable** [comment] 2021-08-17 21:05
Taking a look at the issue, could you provide some more information on the plugins you're generating? It seems that this may be a `protoc`-specific issue: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/command_line_interface.cc#L1447

**Comment by predmond** [comment] 2021-08-17 21:30
Ah good point!

I am using a simple buf.gen.yaml with a single csharp plugin.

**Comment by bufdev** [comment] 2021-08-17 21:51
csharp is actually contained within `protoc`, so this is a `protoc` issue :-)

**Comment by predmond** [comment] 2021-08-18 14:45
@bufdev I just compared with the way we invoke protoc directly. We are using the full path to the file and the problem is avoided. 

Is changing buf to invoke protoc with full paths reasonable? Another option would be to use `./@foo/bar.proto`..

**Comment by bufdev** [comment] 2021-08-18 15:05
Can you provide a reproducible example?

**Comment by predmond** [comment] 2021-08-18 15:26
I realize the `@foo` is odd but it's what I'm working with...

```
$ tree .
.
├── buf.gen.yaml
├── buf.yaml
├── out
└── proto
    └── @foo
        └── bar.proto
```
`buf.gen.yaml`
```yaml
version: v1beta1
plugins:
  - name: csharp
    out: out
```
`buf.yaml`
```yaml
version: v1beta1
build:
  roots:
    - proto
lint:
  use:
    - DEFAULT
  except:
    - FILE_LAYOUT
breaking:
  use:
    - WIRE_JSON
```
`bar.proto`
```proto
syntax = "proto3";
package bar.v1;

message Bar {
}
```

**Comment by bufdev** [comment] 2021-08-19 13:30
I've verified that this works with `protoc`, AND works with `buf protoc`, but does not with `buf generate`.

**Comment by bufdev** [comment] 2021-08-19 13:32
Debugging info:

```
$ buf build -o -#format=json --exclude-source-info
{"file":[{"name":"@foo/bar.proto","package":"bar.v1","messageType":[{"name":"Bar"}],"syntax":"proto3","bufExtension":{"isImport":false,"isSyntaxUnspecified":false}}]}
$ protoc -I proto -o /dev/stdout proto/@foo/bar.proto | buf build -o -#format=json -
{"file":[{"name":"@foo/bar.proto","package":"bar.v1","messageType":[{"name":"Bar"}],"syntax":"proto3","bufExtension":{"isImport":false,"isSyntaxUnspecified":false}}]}
```

**Comment by bufdev** [comment] 2021-08-19 13:35
```
$ protoc -I proto -o /dev/stdout proto/@foo/bar.proto | protoc --descriptor_set_in=/dev/stdin --csharp_out=out @foo/bar.proto
Failed to open argument file: foo/bar.proto

$ protoc -I . -o /dev/stdout proto/@foo/bar.proto | protoc --descriptor_set_in=/dev/stdin --csharp_out=out proto/@foo/bar.proto
# no error
```

This issue seems to be that `buf generate` (properly) strips the root directory when passing as an argument to `protoc`, and if you were to invoke `protoc` with the root directory stripped, the same error happens. I'm actually not sure if there's a mitigation strategy here, this seems like a `protoc` bug still. Investigating.

**Comment by bufdev** [comment] 2021-08-19 14:58
So here's the issue:

- `protoc` accepts files that contain newline-separated flags to `protoc` via `@`, so if you were to have a file `flags.txt` and did `protoc @flags.txt`, it is as if you invoked `protoc` with the flags specified in `flags.txt`.
- If you input `@foo/bar.proto` as a file to `protoc`, it detects `foo/bar.proto` as a flags file.
- Using `protoc -I proto proto/@foo/bar.proto`, this problem doesn't exist, as the file path as passed to `protoc` is detected as `proto/@foo/bar.proto`.
- However, if you instead were inside `proto`, and did `protoc -I . @foo/bar.proto`, the same problem would exist.
- `buf generate` shells out to `protoc` in "plugin mode" i.e. using the `--descriptor_set_in` flag for the "builtin plugins", which includes `csharp`. These are the plugins built into protoc i.e. `java, cpp, python` etc. `buf` produces a `FileDescriptorSet` that is sent to stdin for `protoc`.
- When `buf` creates this `FileDescriptorSet`, it strips the root paths (correctly, this is what `protoc` would do as well), so the `proto` is stripped, and `@foo/bar.proto` is given as the file path.

There's basically no good solution to this. We could in theory append a fake directory path to all file paths in the `FileDescriptorSet`, but this would affect code generation. Your only options are:

1. Get the github.com/protocolbuffers/protobuf` maintainers to change the `@` behavior, however spoiler alert: they won't, as this would be a breaking change, and this behavior has been around for more than a decade.
2. Use `protoc` or `buf protoc` and make sure that the file paths you pass in start with `proto/`.
3. Change your file names.

Overall, having file names with `@` in them is going to be buggy when using anything related to `protoc`.

Closing as there's nothing to really fix here unfortunately.

**Closed by bufdev** 2021-08-19 14:58 UTC
Labels: Bug, P0
