### ISSUE TITLE
--version outputs to stderr

### ISSUE THREAD

**Issue by aastein** [bufbuild/buf#379] opened 2021-07-21 18:23 UTC
`buf --version` outputs to stderror, expected stdout

**Comment by bufdev** [comment] 2021-07-21 18:25
Duplicate of https://github.com/bufbuild/buf/issues/258 and https://github.com/bufbuild/buf/issues/135

**Closed by bufdev** 2021-07-21 18:25 UTC
Labels: Duplicate, Working as intended

**Comment by bufdev** [comment] 2021-09-15 16:43
We've moved `--version` to stdout for v1, as an FYI!
