### ISSUE TITLE
Buf format reported to add whitespace within commented-out lines

### ISSUE THREAD

**Issue by cedarkeith** [bufbuild/buf#3005] opened 2024-05-21 20:27 UTC
buf-format, running as part of my pre-commit hooks, regularly adds whitespace to blank lines inside multi-line comment sections.

I have a .proto file formatted like this:
```proto
message SomeMessage {
  bool exists = 1;
}
/*
      message CommentedOutMessage {
        repeated int32 field_1 = 1;
      }


      message CommentedOutMessage2 {
      }
   message MyOtherMessage {
   int32 field_1 = 1;
   }
*/

// ================ END SECTION ================
```

When the pre-commit hooks run, buf-format adds tabs on the two lines between CommentedOutMessage and CommentedOutMessage2. 

Comment sections should probably be ignored by buf-format.

**Comment by bufdev** [comment] 2024-05-21 20:35
I'm unable to reproduce with `buf format -w` - we're not sure why the pre-commit hook would be different. Can you provide a specific, reproducible example (for example, in a temporary github repository) with steps to reproduce?

**Comment by bufdev** [comment] 2024-05-23 15:12
Closing as we haven't been able to reproduce - if you can provide us with a specific, reproducible example, let us know and we'll be happy to investigate!

**Closed by bufdev** 2024-05-23 15:12 UTC
Labels: Needs clarification
