### ISSUE TITLE
Allow a custom package prefix for `PACKAGE_DIRECTORY_MATCH` lint rule

### ISSUE THREAD

**Issue by stabai** [bufbuild/buf#1122] opened 2022-05-11 04:58 UTC
While the general functionality of the `PACKAGE_DIRECTORY_MATCH` lint rule is great, it would be nice if users could provide an expected prefix in proto packages.

For example, if I have my `buf.yaml` file in `/proto`, and a proto file in `/proto/foo/v1/`, it will force its proto package to be exactly `foo.v1`. But it might be ideal for it to have some prefix added to that, like `mycompany.proto.foo.v1`.

**Comment by bufdev** [comment] 2022-05-11 15:09
Duplicate of https://github.com/bufbuild/buf/issues/149 and https://github.com/bufbuild/buf/issues/232

**Closed by bufdev** 2022-05-11 15:09 UTC
