### ISSUE TITLE
Exclude vendor directory

### ISSUE THREAD

**Issue by DeOne4eg** [bufbuild/buf#1174] opened 2022-06-06 15:27 UTC
```
go version 1.17.7
buf 1.15.0
```

```
# buf.work.yaml
version: v1
directories:
  - api
```

I have a problem with buf breaking. I can't exclude vendor from comparison, I want to compare only the api directory, but it still checks vendor.

Command:
`buf breaking api --against .git\#branch=master --error-format=json`

```
|--api
| |--user.proto
|--vendor
| |--another.proto
```

Error
```
{"path":"vendor/another.proto","start_line":5,"start_column":8,"end_line":5,"end_column":8,"type":"COMPILE","message":"gogoproto/gogo.proto: does not exist"}
make: *** [buf-breaking] Error 100
```

What am I doing wrong?

**Comment by robbertvanginkel** [comment] 2022-06-06 15:51
Thank you for the report! Could you be more specific in your reproduction steps about your setup? I cannot reproduce with the following:
```
$ mkdir api vendor
$ cat > vendor/bar.proto << EOF
syntax = "proto3";
package pkg.vendor;
message Bar{}
EOF
$ cat > api/foo.proto << EOF
syntax = "proto3";
package pkg;
message Foo{}
EOF
$ cat > buf.work.yaml << EOF
version: v1
directories:
  - api
EOF
$ git init && git add . && git commit -m "init"
[main (root-commit) d7ac3ce] init
 3 files changed, 9 insertions(+)
 create mode 100644 api/foo.proto
 create mode 100644 buf.work.yaml
 create mode 100644 vendor/bar.proto
$ echo 'import "gogoprotobuf/gogo.proto";' >> vendor/bar.proto 
$ buf breaking api --against .git\#branch=main --error-format=json && echo $?
0
```
This only errors if I specifically indicate that vendor should be checked:
```
$ buf breaking vendor --against .git\#branch=main --error-format=json
{"path":"vendor/bar.proto","start_line":4,"start_column":8,"end_line":4,"end_column":8,"type":"COMPILE","message":"gogoprotobuf/gogo.proto: does not exist"}
```

**Comment by robbertvanginkel** [comment] 2022-06-06 22:58
The demo repository does not seem to contain a `buf.work.yaml` file. Without that, buf will attempt to build the whole repository at the commit on the provided ref.

After adding a buf.work.yaml into the demo repository, this passes for me:
```
$ git clone https://github.com/DeOne4eg/buf-breaking-issue.git && cd buf-breaking-issue
$ echo 'version: v1\ndirectories:\n  - first\n' > buf.work.yaml
$ git add . && git commit --amend --noedit
$ buf breaking first --against .git\#branch=master --error-format=json
```

**Comment by bufdev** [comment] 2022-06-09 20:56
Given the above, closing this issue for now.

**Closed by bufdev** 2022-06-09 20:56 UTC
