### ISSUE TITLE
Failure: context canceled.

### ISSUE THREAD

**Issue by dreamans** [bufbuild/buf#439] opened 2021-08-20 09:09 UTC
Unable to connect to api.buf.build from China. 

More Info:

```
$ buf generate -v
DEBUG	get_ref	{"duration": "590.29µs"}
DEBUG	get_config	{"duration": "1.411681ms"}
DEBUG	get_config	{"duration": "422.695µs"}
DEBUG	get_config	{"duration": "418.363µs"}
WARN	Specified deps are not covered in your buf.lock, run "buf mod update":
	- github.com/googleapis/googleapis
DEBUG	get_module_config	{"duration": "6.599485ms"}
DEBUG	cache_miss	{"module_pin": "buf.build/googleapis/googleapis:d6ee4a74dbb44a97a6aa716ba9db6561"}
buf: downloading buf.build/googleapis/googleapis:d6ee4a74dbb44a97a6aa716ba9db6561
DEBUG	grpcclient	dial	{"address": "dns:///api.buf.build"}
^CDEBUG	buf.alpha.registry.v1alpha1.DownloadService.Download	{"duration": "2.188928793s", "Client": true, "FailFast": true}
DEBUG	command	{"duration": "2.636177481s"}
Failure: context canceled.
```

**Comment by bufdev** [comment] 2021-08-20 13:40
Duplicate of https://github.com/bufbuild/buf/issues/277

**Closed by bufdev** 2021-08-20 13:40 UTC
