### ISSUE TITLE
make `buf` compatible with `protoc-gen-elixir` from the `protobuf` package

### ISSUE THREAD

**Issue by jvantuyl** [bufbuild/buf#2512] opened 2023-10-24 19:02 UTC
I've been trying to use [Elixir's `protobuf` package](https://github.com/elixir-protobuf/protobuf) with `buf`.  It implements a `protoc-gen-elixir` binary that mostly works.

One of its features is "add a prefix to generated modules".  This is very useful, as BEAM tolerates duplicate modules rather badly.  We've been sidestepping this by using a feature to add a prefix to all generated modules.  So, if there is any overlap, we just have two versions of what's really the same protocol buffer schema.

This works flawlessly with `protoc` but not with `buf`.  It took me a while to figure out why.  It appears that `protoc-gen-elixir` requires all of the files to be generated in the same run.  And, I think, (and correct me if I'm wrong about this) `buf` may not do this?

After some digging, it looks like they actually do this for a pretty good reason—well-known types.  They don't just have to prefix the names of the modules, they also have to prefix the references.  Since well-known-types won't have those prefixes, they need to discern the difference.  They do this by checking to see if a given reference is for something that we're building elsewhere in the same run.

Since `protoc` typically gets used as a single run, this works fine there.  I can't seem to get this working with `buf`.

Do we have a workaround?  Or is there a fix we could do for this?

**Comment by smallsamantha** [comment] 2023-10-24 19:07
Hi @jvantuyl! I haven't taken a deep look into `protoc-gen-elixir` so I'm just basing this suggestion on your given information (thank you for the detail by the way) but have you experimented with the buf.gen.yaml [strategy](https://buf.build/docs/configuration/v1/buf-gen-yaml#strategy) at all? If the issue is as you describe, related to the plugin invocation happening on all input files in one run, I think you may need to set the strategy to `all`.

**Comment by jvantuyl** [comment] 2023-10-24 19:11
I have *not* seen that. I'll try that!

**Comment by smallsamantha** [comment] 2023-11-17 15:27
Hi @jvantuyl - closing this issue for now, please let us know if you run into anything else!

**Closed by smallsamantha** 2023-11-17 15:27 UTC
