### ISSUE TITLE
panic while generating: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by brumer** [bufbuild/buf#210] opened 2020-12-07 13:06 UTC
I got a panic after installing buff from source `go get -u github.com/bufbuild/buf/cmd/buf` and running buf generate.

```
panic: runtime error: invalid memory address or nil pointer dereference, stack:
goroutine 9 [running]:
runtime/debug.Stack(0xc0003b8c10, 0x17a1260, 0x1dba320)
        /usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x9f
github.com/bufbuild/buf/internal/buf/bufcore/bufimage/bufimagebuild.getBuildResults.func1.2(0xc0003b9f58)
        /Users/moshe_brumer/go/pkg/mod/github.com/bufbuild/buf@v0.32.0/internal/buf/bufcore/bufimage/bufimagebuild/builder.go:155 +0x5e
panic(0x17a1260, 0x1dba320)
        /usr/local/opt/go/libexec/src/runtime/panic.go:969 +0x1b9
github.com/jhump/protoreflect/dynamic.(*Message).findMissingFields(0x0, 0xc000000003, 0xc0001f2480, 0xc0001175f0)
        /Users/moshe_brumer/go/pkg/mod/github.com/jhump/protoreflect@v1.7.1/dynamic/dynamic_message.go:2612 +0x37
github.com/jhump/protoreflect/dynamic.(*Message).validateRecursive(0x0, 0xc0000bfa00, 0x72, 0x72, 0xc0003b9118)
        /Users/moshe_brumer/go/pkg/mod/github.com/jhump/protoreflect@v1.7.1/dynamic/dynamic_message.go:2635 +0x45
github.com/jhump/protoreflect/dynamic.(*Message).validateRecursive.func1(0x19675c0, 0x0, 0x0, 0x19675c0)
        /Users/moshe_brumer/go/pkg/mod/github.com/jhump/protoreflect@v1.7.1/dynamic/dynamic_message.go:2656 +0x6a
github.com/jhump/protoreflect/dynamic.(*Message).validateRecursive(0xc00020edb0, 0xc000190a00, 0x4a, 0x4a, 0xc0003b93b0)
        /Users/moshe_brumer/go/pkg/mod/github.com/jhump/protoreflect@v1.7.1/dynamic/dynamic_message.go:2667 +0x4a2
github.com/jhump/protoreflect/dynamic.(*Message).validateRecursive.func1(0x19675c0, 0xc00020edb0, 0xc00020edb0, 0x19675c0)
        /Users/moshe_brumer/go/pkg/mod/github.com/jhump/protoreflect@v1.7.1/dynamic/dynamic_message.go:2656 +0x6a
github.com/jhump/protoreflect/dynamic.(*Message).validateRecursive(0xc00020eba0, 0xc00055a000, 0x3e, 0x3e, 0xc0003b9648)
        /Users/moshe_brumer/go/pkg/mod/github.com/jhump/protoreflect@v1.7.1/dynamic/dynamic_message.go:2677 +0x92b
github.com/jhump/protoreflect/dynamic.(*Message).validateRecursive.func1(0x19675c0, 0xc00020eba0, 0xc00020eba0, 0x19675c0)
        /Users/moshe_brumer/go/pkg/mod/github.com/jhump/protoreflect@v1.7.1/dynamic/dynamic_message.go:2656 +0x6a
github.com/jhump/protoreflect/dynamic.(*Message).validateRecursive(0xc00020eae0, 0x0, 0x0, 0xc00012bba8, 0xc00020eae0)
        /Users/moshe_brumer/go/pkg/mod/github.com/jhump/protoreflect@v1.7.1/dynamic/dynamic_message.go:2683 +0xadc
github.com/jhump/protoreflect/dynamic.(*Message).ValidateRecursive(...)
        /Users/moshe_brumer/go/pkg/mod/github.com/jhump/protoreflect@v1.7.1/dynamic/dynamic_message.go:2631
github.com/jhump/protoreflect/desc/protoparse.interpretOptions(0xc000369560, 0x29bd2c18, 0xc00030fb20, 0x1968400, 0xc000221d10, 0xc000378bc0, 0x5, 0x8, 0x0, 0x0, ...)
        /Users/moshe_brumer/go/pkg/mod/github.com/jhump/protoreflect@v1.7.1/desc/protoparse/options.go:988 +0xacb
github.com/jhump/protoreflect/desc/protoparse.interpretFileOptions(0xc000369560, 0x1973940, 0xc00030fb20, 0x2a, 0xc00011acc8)
        /Users/moshe_brumer/go/pkg/mod/github.com/jhump/protoreflect@v1.7.1/desc/protoparse/options.go:685 +0x6cc
github.com/jhump/protoreflect/desc/protoparse.(*linker).linkFiles(0xc000378c00, 0xc000378c00, 0x7, 0x7)
        /Users/moshe_brumer/go/pkg/mod/github.com/jhump/protoreflect@v1.7.1/desc/protoparse/linker.go:66 +0x1b4
github.com/jhump/protoreflect/desc/protoparse.Parser.ParseFiles(0x0, 0x0, 0x0, 0x0, 0x0, 0xc0004d18e0, 0x1, 0xc0004d1900, 0x0, 0xc0003fbf10, ...)
        /Users/moshe_brumer/go/pkg/mod/github.com/jhump/protoreflect@v1.7.1/desc/protoparse/parser.go:215 +0x271
github.com/bufbuild/buf/internal/buf/bufcore/bufimage/bufimagebuild.getBuildResult(0x196a6c0, 0xc0004b5a70, 0x1967240, 0xc000330dc0, 0xc0003fbf10, 0x7, 0x7, 0x0, 0x0)
        /Users/moshe_brumer/go/pkg/mod/github.com/bufbuild/buf@v0.32.0/internal/buf/bufcore/bufimage/bufimagebuild/builder.go:200 +0x1c5
github.com/bufbuild/buf/internal/buf/bufcore/bufimage/bufimagebuild.getBuildResults.func1(0xc0004bc5a0, 0xc0004bad40, 0x1967240, 0xc000330dc0, 0xc0003fbf10, 0x7, 0x7, 0xc0004ce600)
        /Users/moshe_brumer/go/pkg/mod/github.com/bufbuild/buf@v0.32.0/internal/buf/bufcore/bufimage/bufimagebuild/builder.go:159 +0xff
created by github.com/bufbuild/buf/internal/buf/bufcore/bufimage/bufimagebuild.getBuildResults
        /Users/moshe_brumer/go/pkg/mod/github.com/bufbuild/buf@v0.32.0/internal/buf/bufcore/bufimage/bufimagebuild/builder.go:140 +0x266
```

**Comment by bufdev** [comment] 2020-12-07 14:07
Without reproduction information, we can’t help - please provide steps to reproduce, including files that cause this.

**Comment by brumer** [comment] 2020-12-07 15:03
After some tinkering with my proto files, I managed to find the culprit.
If the following file is included in the proto folder then buf panics

```
syntax = "proto3";

package com.sac.saml_configuration_service.api.internal_api.v1;
import "protoc-gen-openapiv2/options/annotations.proto";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
	info: {
		title: "Service REST API"
		version: "0.0.1"
	}
	security_definitions: {
		security: {
			key: "Identifier"
			value: {
				type: TYPE_API_KEY
				in: IN_HEADER
				name: "X-ID"
			}
		}
	}
	security: {
		security_requirement: {
			key: "Tenant Identifier"
		}
	}
	consumes: "application/json"
	produces: "application/json"
	schemes: HTTP
	responses: {
		key: "400"
		value: {
			description: "Invalid request parameters."
		}
	}
	responses: {
		key: "500"
		value: {
			description: "Internal service error"
		}
	}
};

```

**Comment by bufdev** [comment] 2020-12-07 15:36
We still can't reproduce a panic here with just that file and the grpc-gateway imports, can you please provide us a full reproduction case where this results in a panic when running `buf generate`?

**Comment by bufdev** [comment] 2020-12-07 16:48
The problem is that you were using `go get -u` instead of `go get`, which resulted in the master version of github.com/jhump/protoreflect, instead of the version used by buf releases. The bug above was fixed in buf a few months ago. However, https://github.com/jhump/protoreflect/releases/tag/v1.8.0 was just created, which will make it so that `go get -u` gets a version with this bug fixed, so this should be resolved.

**Closed by bufdev** 2020-12-07 16:48 UTC
