### ISSUE TITLE
Allow package name prefix for PACKAGE_DIRECTORY_MATCH lint check

### ISSUE THREAD

**Issue by martinxsliu** [bufbuild/buf#232] opened 2021-01-05 02:10 UTC
Hi there, I would like to make a feature request to allow specifying a prefix for the `PACKAGE_DIRECTORY_MATCH` linter check, e.g. a `lint.package_prefix` option.

We have a convention where we prefix all of our protobuf packages with a (company specific) segment that's not present in the directory structure. Apart from this prefix though, we do want to enforce that the directory structure matches the rest of the package path. I can also see this being useful for protos that have been moved around from one directory or repo to another, e.g. for legacy reasons or otherwise.

In the following example, the custom prefix is `my_protos` and the remainder of the package name `foo.data` should match the directory `foo/data/`.

```protobuf
// foo/data/item.proto
syntax = "proto3";
package my_protos.foo.data;
```

Some considerations are:
* Should we assume that the prefix is separated with a `.` or not? e.g. in the above example, should the prefix be `my_protos` or `my_protos.`?
* How would this work with multiple roots? I'm not familiar with the behaviour of this lint check with multiple roots, but assuming that we can strip off the prefix from the package name, the rest should be the same.
* Should we also support the opposite feature, where instead of stripping off a prefix from the package name before comparing, we would add a prefix instead? This may occur if all or most protos live in a nested directory within the root, but with import statements relative to the root such that you can't simply change the root config in the config file. I feel like this is a much more unlikely scenario that may not be worth supporting, but we should consider for completeness.

**Comment by bufdev** [comment] 2021-01-05 02:17
Duplicate of https://github.com/bufbuild/buf/issues/149 - in short, we’ve considered this feature extensively, but we think the drawbacks outweigh the benefits, our apologies.

**Closed** 2021-01-05 02:21 UTC
Labels: Duplicate
