### ISSUE TITLE
Fix error message "failed to generate plugins concurrently"

### ISSUE THREAD

**Issue by bufdev** [bufbuild/buf#559] opened 2021-09-16 15:03 UTC
`Failure: failed to generate plugins concurrently: failed to create handler: could not find protoc plugin for name debug`

The error should just be `could not find protoc plugin for name debug`. https://github.com/bufbuild/buf/pull/500 introduced additional error wrapping, we should remove it

**Comment by johanbrandhorst** [comment] 2021-09-16 15:04
Dupe of #541?

**Closed** 2021-09-16 15:10 UTC
Labels: Cleanup, P0
