### ISSUE TITLE
timestamps incompatible across versions

### ISSUE THREAD

**Issue by tgross** [bufbuild/buf#315] opened 2021-05-05 15:50 UTC
In [Nomad](https://github.com/hashicorp/nomad/) we're using `buf` and ran into a panic when communicating between a Nomad agent a Nomad plugin built using different versions of `buf` because of the change in the default timestamp type. I've extracted a minimal reproduction to https://github.com/tgross/bufbreaks

If the timestamp type isn't wire compatible between `github.com/golang/protobuf/ptypes/timestamp` and `google.golang.org/protobuf/types/known/timestamppb` that's obviously an unfortunate choice by upstream, but I would have expected `buf` not to change the type in an incompatible way. 

```
$ make test
go build -trimpath -tags old -o bin/old .
go build -trimpath -tags new -o bin/new .
./bin/old write
./bin/new read
panic: protobuf tag not enough fields in Timestamp.state:

goroutine 1 [running]:
github.com/golang/protobuf/proto.(*unmarshalInfo).computeUnmarshalInfo(0xc0000ce460)
        github.com/golang/protobuf@v1.5.0/proto/table_unmarshal.go:332 +0x1777
github.com/golang/protobuf/proto.(*unmarshalInfo).unmarshal(0xc0000ce460, 0xc0000b2240, 0xc0000ee00d, 0xb, 0x1f3, 0xc0000ee004, 0x7)
        github.com/golang/protobuf@v1.5.0/proto/table_unmarshal.go:136 +0xf45
github.com/golang/protobuf/proto.makeUnmarshalMessagePtr.func1(0xc0000ee00d, 0xb, 0x1f4, 0xc0000b2210, 0x2, 0xc0000ee00b, 0xd, 0x1f5, 0x0, 0x0)
        github.com/golang/protobuf@v1.5.0/proto/table_unmarshal.go:1646 +0x12b
github.com/golang/protobuf/proto.(*unmarshalInfo).unmarshal(0xc0000ce3c0, 0xc0000b2200, 0xc0000ee002, 0x16, 0x1fe, 0x0, 0x12aa320)
        github.com/golang/protobuf@v1.5.0/proto/table_unmarshal.go:173 +0x88e
github.com/golang/protobuf/proto.makeUnmarshalMessagePtr.func1(0xc0000ee002, 0x16, 0x1ff, 0xc00009c870, 0x2, 0xc0000c5d68, 0x756ea1d8d90c87, 0x203000, 0x203000, 0x203000)
        github.com/golang/protobuf@v1.5.0/proto/table_unmarshal.go:1646 +0x12b
github.com/golang/protobuf/proto.(*unmarshalInfo).unmarshal(0xc0000ce320, 0xc00009c870, 0xc0000ee000, 0x18, 0x200, 0x100a06c, 0x141c920)
        github.com/golang/protobuf@v1.5.0/proto/table_unmarshal.go:173 +0x88e
github.com/golang/protobuf/proto.(*InternalMessageInfo).Unmarshal(0x13eea20, 0x12a7108, 0xc00009c870, 0xc0000ee000, 0x18, 0x200, 0x4a31901, 0x4a39058)
        github.com/golang/protobuf@v1.5.0/proto/table_unmarshal.go:63 +0x66
main.(*TaskStatsResponse).XXX_Unmarshal(0xc00009c870, 0xc0000ee000, 0x18, 0x200, 0xc00009c870, 0xc0000c5e01)
        bufbreaks/structs.new.pb.go:41 +0x65
github.com/golang/protobuf/proto.Unmarshal(0xc0000ee000, 0x18, 0x200, 0x12a7108, 0xc00009c870, 0xc0000c5f40, 0x11f8f7a)
        github.com/golang/protobuf@v1.5.0/proto/decode.go:337 +0x1aa
main.deserialize(0xc0000ee000, 0x18, 0x200)
        bufbreaks/serde.new.go:33 +0x85
main.main()
        bufbreaks/main.go:34 +0xcb
make: *** [test] Error 2
```

**Comment by bufdev** [comment] 2021-05-05 16:06
Nothing has changed about the the structure of [google.protobuf.Timestamp](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/timestamp.proto), except Google did introduce a change to the `go_package` value, updating it to point to `google.golang.org/protobuf/types/known/timestamppb`, which is a breaking change. This shouldn't affect your above code, however - this has nothing to do with serialization or the wire compatibility of `Timestamp`.

Looking through https://github.com/tgross/bufbreaks/blob/trunk/serde.new.go, it appears you are using the old `github.com/golang/protobuf/proto` with the new `Timestamp` type, which could cause a problem, you should be using the new https://pkg.go.dev/google.golang.org/protobuf/proto#Marshal with new types, this could cause a problem.

As to `buf` not breaking here, we actually agree - we don't think a change should have been made to the Well-Known Types, ever, but are hands of kind of tied here. The Protobuf ecosystem relies on the WKTs being built-in to the compiler (although `protoc` relies on them being at `../include` relative to the binary, which is even more broken), and Google made this upgrade. If there was a wire incompatibility (which there is not here, your problem is something else), and you use `protoc` in a similar way, it will break as well.

One way to solve this, if you are concerned with WKT breakages, is to vendor the WKTs yourself:

```
# This is actually the best way, not kidding
$ mkdir -p tmp && \
  cd ./tmp && \
  curl -sSL https://github.com/protocolbuffers/protobuf/releases/download/v3.15.8/protoc-3.15.8-linux-x86_64.zip -o protoc.zip && \
  unzip protoc.zip >/dev/null && \
  mv ./include/google ~/your/repo/third_party/proto/google
```

And then add `third_party/proto` as a root:

```
# buf.yaml
version: v1beta1
build:
  roots:
    - third_party/proto
```

If you have the WKTs included yourself, both `buf` and `protoc` will ignore their builtins and use these instead.

Of note though, WKTs have never had a wire-incompatible change in over a decade.

**Comment by bufdev** [comment] 2021-05-06 15:44
Closing this as there's no action to be taken here, just a rough summary.

- Buf provides the Well-Known Types as builtin types, similar to protoc.
- On protoc v3.14.0, the `go_package` value changed for the Well-Known Types, and `google.protobuf.Timestamp` now pointing to https://pkg.go.dev/google.golang.org/protobuf/types/known/timestamppb instead of https://pkg.go.dev/github.com/golang/protobuf/ptypes.
- While Buf considers a change in `go_package` to be a breaking change, it also needs to match protoc in this instance, so Buf upgraded the Well-Known Types to match protoc.
- The new `timestamppb` package uses v2 of golang/protobuf at google.golang.org/protobuf. Versions of golang/protobuf >=1.4.0 use google.golang.org/protobuf under the hood.
- There is an issue using generated code from golang/protobuf versions <1.4.0 with the marshal/unmarshal functions of golang/protobuf versions >1.4.0, or google.golang.org/protobuf.
- The referenced reproduction was intermixing the two, resulting in a serialization error.
- `google.protobuf.Timestamp` itself has not changed, and https://github.com/tgross/bufbreaks/pull/1, https://github.com/tgross/bufbreaks/pull/2 show two mitigation strategies that show there is no wire incompatibility.
- Buf needs to continue to match the WKT behavior of protoc, and this same behavior would be witnessed if the same usage was applied for a customer upgrading from protoc v3.13.0 to v3.14.0, and Buf is working as intended here.

More discussion is on https://github.com/hashicorp/nomad/issues/10293.

**Closed by bufdev** 2021-05-06 15:44 UTC
