### ISSUE TITLE
Can't build PHP clients

### ISSUE THREAD

**Issue by jasperweyne** [bufbuild/buf#2080] opened 2023-05-12 19:43 UTC
I'm trying to setup a PHP client using buf. Defining messages works great, but I'm running into issues when creating a service definition.
```yaml
# buf.yaml
version: v1
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
```
```yaml
# buf.gen.yaml
version: v1
managed:
  enabled: true
plugins:
  - plugin: buf.build/grpc/php:v1.54.2
    out: gen
  - plugin: buf.build/protocolbuffers/php
    out: gen
```
```proto
// helloworld.proto
syntax = "proto3";

service Greeter {
  rpc Hello (HelloRequest) returns (HelloReply) {}
}

message HelloRequest {
  string message = 1;
}

message HelloReply {
  string message = 1;
}
```

```bash
> buf generate --verbose --debug
DEBUG   get_ref {"duration": "526.8µs"}
DEBUG   get_config      {"duration": "6.4806ms"}
DEBUG   get_config      {"duration": "546.4µs"}
DEBUG   get_config      {"duration": "0s"}
DEBUG   get_module_config       {"duration": "2.8796ms"}
DEBUG   get_image       {"duration": "0s"}
DEBUG   build   {"duration": "1.1368627s"}
DEBUG   build_module    {"duration": "1.1368627s"}
DEBUG   command {"duration": "3.3961434s"}
Failure: plugin buf.build/grpc/php:v1.54.2: /GreeterClient.php: expected to be relative
```

I'm running this command on Windows 11. How can I solve this issue?

**Comment by bufdev** [comment] 2023-05-15 15:42
The core of the issue is actually a github.com/grpc/grpc bug, not a `buf` bug.

It appears that when no `package` is defined in a `.proto` file, the gRPC PHP plugin produces an invalid response. See https://github.com/protocolbuffers/protobuf/blob/95e6c5b4746dd7474d540ce4fb375e3f79a086f8/src/google/protobuf/compiler/plugin.proto#L122 - the plugin should produce a relative path with no `..`'s, but instead is producing an absolute path. `buf` validates for this, while `protoc` does not.

- The mitigation for you is to add a package definition, i.e. `package hello;`. If you do this, everything will just work, and in almost all cases you will have a package definition anyways.
- The right solution is for the github.com/grpc/grpc team to conform to the `CodeGeneratorResponse` specification as linked above. I believe the issue is that when there is no package defined, they produce a leading `/` for the file name, when it should be i.e. `GreeterClient.php` (instead of `/GreeterClient.php).
- Within `buf`, we also may want to relax our constraints slightly to allow for this. We'll investigate this avenue as well.

**Comment by bufdev** [comment] 2023-05-16 00:06
This was fixed in https://github.com/grpc/grpc/pull/33126, this should go out in a future grpc release. Let us know if this end up blocking you, all of your Protobuf files should have packages in general though.

**Closed** 2023-05-16 00:06 UTC
