### ISSUE TITLE
Failed Using Buf's Docker Image to Generate Code

### ISSUE THREAD

**Issue by zhanp** [bufbuild/buf#511] opened 2021-09-07 08:48 UTC
I am trying to use buf's docker image to generate code just like the doc said:
https://docs.buf.build/generate/usage#docker

It failed and camp up an error log:
Failure: failed to generate plugins concurrently: failed to create handler: could not find protoc plugin for name go.

So how can I use it to generate code if there is no protoc plugin installed?

**Comment by bufdev** [comment] 2021-09-07 13:18
Duplicate of https://github.com/bufbuild/buf/issues/184 and https://github.com/bufbuild/buf/issues/228

**Closed by bufdev** 2021-09-07 13:18 UTC
Labels: Duplicate
