### ISSUE TITLE
brew install bufbuild/buf/buf is fail

### ISSUE THREAD

**Issue by sjhector** [bufbuild/buf#1176] opened 2022-06-07 12:45 UTC
device: apple m1 pro

**Comment by robbertvanginkel** [comment] 2022-06-07 14:11
Just tried on an m1 and I cannot reproduce:

```
$ brew install bufbuild/buf/buf
==> Downloading https://ghcr.io/v2/homebrew/core/go/manifests/1.18.2
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/go/blobs/sha256:5a1b5411dad51d04469800db4107be6318bb797b693c29d9301d62a91f6d3d2e
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:5a1b5411dad51d04469800db4107be6318bb797b693c29d9301d62a91f6d3d2e?se=2022-06-07T14%3A15%3A00Z&sig=4OPOFkffZJjv8P
######################################################################## 100.0%
==> Downloading https://github.com/bufbuild/buf/archive/v1.5.0.tar.gz
==> Downloading from https://codeload.github.com/bufbuild/buf/tar.gz/refs/tags/v1.5.0
##=#=#
==> Installing buf from bufbuild/buf
==> Installing dependencies for bufbuild/buf/buf: go
==> Installing bufbuild/buf/buf dependency: go
==> Pouring go--1.18.2.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/go/1.18.2: 11,976 files, 595.9MB
==> Installing bufbuild/buf/buf
==> sh make/buf/scripts/brew.sh .build/brew
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Summary
🍺  /opt/homebrew/Cellar/buf/1.5.0: 75 files, 49.1MB, built in 19 seconds
==> Running `brew cleanup buf`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Caveats
==> buf
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
$ brew info buf
bufbuild/buf/buf: stable 1.5.0, HEAD
A new way of working with Protocol Buffers.
https://buf.build
/opt/homebrew/Cellar/buf/1.5.0 (75 files, 49.1MB) *
  Built from source on 2022-06-07 at 10:08:20
```

Closing for now as there isn't really any details to go on in the report. If you can supply a log with more details or ideally a reproduction we can re-open.

**Closed by robbertvanginkel** 2022-06-07 14:11 UTC
