### ISSUE TITLE
Custom lint rule - Force specific custom method option on rpc methods

### ISSUE THREAD

**Issue by kostyay** [bufbuild/buf#993] opened 2022-03-10 16:42 UTC
Hi
We would like to add a linter that would make sure we didnt forget adding a custom method option to our methods in a specific proto file.
```proto
service Users {
    rpc InviteUser(InviteUserRequest) returns (User) {
       option (internal.authz) = {scopes: ["user.write"]}; // <---- I want to verify this exists on all methods in this service
    }
}
```
Any suggestions how to approach this?

**Comment by amckinney** [comment] 2022-03-10 18:26
This is a duplicate of https://github.com/bufbuild/buf/issues/29 - we don't plan to support custom lint rules.

As for how to go about this in general, you can write a simple linter as a Protobuf plugin (like we do with [`protoc-gen-buf-lint`](https://docs.buf.build/reference/protoc-plugins)) and invoke it with a `buf.gen.yaml` specifically tailored to linting. We'll name it `buf.gen.lint.yaml` for clarity.

For example,

```yaml
# buf.gen.lint.yaml
version: v1
plugins:
  - name: custom-lint # This assumes your plugin is named 'protoc-gen-custom-lint'.
     out: .
```

```sh
$ buf generate --template buf.gen.lint.yaml
```

In your case, the plugin would be simple - iterate over each of the `rpc` definitions, and verify that the custom option is set. You'll need to compile the custom option definition into the plugin implementation (so that you can recognize when the option is set).

A lot of this is actually described in our API Specifications Conference tutorial [here](https://www.youtube.com/watch?v=NYQXNTwtSzk). Check it out and hopefully that helps you get started!

**Closed by amckinney** 2022-03-10 18:26 UTC
