### ISSUE TITLE
Why is the protoc version sometimes (unknown)?

### ISSUE THREAD

**Issue by veith** [bufbuild/buf#903] opened 2022-02-01 16:53 UTC
The produced files differs only in the comment section with the protoc version information. 

This results in a change in every pb.go produced, which makes the commit confusing because it suggests that every file has been changed.

buf 1.0.0-rc11 on alpine linux (installed with [binary](https://docs.buf.build/installation#binary) )
```proto
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: abac/abac.proto
```

buf 1.0.0-rc11 on macos (installed with brew)
```proto
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: abac/abac.proto
```

**Comment by amckinney** [comment] 2022-02-01 16:58
Duplicate of https://github.com/bufbuild/buf/issues/813

**Comment by amckinney** [comment] 2022-02-01 16:59
Now that I've reviewed this a bit, the issue actually looks different - are you sure that you're using `-rc11` in both cases? This change should have affected previous release candidates.

**Comment by amckinney** [comment] 2022-02-02 00:25
Feel free to re-open this if there is a real problem on `-rc11`.

**Closed by amckinney** 2022-02-02 00:25 UTC
