### ISSUE TITLE
Error while "buf generate"

### ISSUE THREAD

**Issue by abhi021** [bufbuild/buf#294] opened 2021-03-25 12:41 UTC
buf: downloading buf.build/beta/googleapis:aced890b7e944f9ca174481ad810ca5f

**Comment by johanbrandhorst** [comment] 2021-03-25 12:53
Hi @abhi021, what is the error exactly? It's common for CLI tools to output log messages like this to `STDERR` instead of `STDOUT` to allow users to redirect output without having to filter out these messages.

**Comment by abhi021** [comment] 2021-03-26 06:02
Failed to "generate": the server hosted at that remote is unavailable: transport is closing.

**Comment by johanbrandhorst** [comment] 2021-03-26 12:15
Could you share what your `buf.yaml` file looks like? We've seen used accidentally use `github.com` in their `deps` or `name`, which can cause this error.

**Comment by xkisu** [comment] 2021-03-27 17:09
I'm encountering this as well with 0.40.0

```yaml
version: v1beta1

name: buf.build/example/exampleproject

deps:
  - buf.build/beta/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway

build:
  roots:
    - proto

lint:
  use:
    - DEFAULT

breaking:
  use:
    - FILE
    - WIRE_JSON
```

**Comment by bufdev** [comment] 2021-03-27 17:10
What are you experiencing? Please provide the output. The “downloading” message is not an error and is as expected.

**Comment by xkisu** [comment] 2021-03-27 17:52
The same as what @abhi021 posted

```
buf: downloading buf.build/beta/googleapis:aced890b7e944f9ca174481ad810ca5f
Failed to "generate": the server hosted at that remote is unavailable: transport is closing.
```

And then buf exits and doesn't generate and code. If I copy the `lock` and `mod` folders generated by buf from an existing project it doesn't attempt to download the dependencies and works, but if I don't then it completely fails downloading.

**Comment by johanbrandhorst** [comment] 2021-03-28 07:31
It sounds like your computer can't talk to `buf.build`. Other users have seen this sort of error when they used `github.com` as a remote by mistake. Could you make sure all the hosts for all your module names and dependencies are referring to `buf.build`?

**Comment by abhi021** [comment] 2021-03-30 15:29
@johanbrandhorst 

buf :  0.40.0
`version: v1beta1
name: buf.build/yourorg/yourprotos
deps:
  - buf.build/beta/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
 `
Error: 
buf: downloading buf.build/beta/googleapis:aced890b7e944f9ca174481ad810ca5f
Failed to "generate": the server hosted at that remote is unavailable: transport is closing.

Still getting the same error. Can we check the access of `buf.build`

**Comment by johanbrandhorst** [comment] 2021-03-30 16:06
It looks like your network access to `buf.build` is blocked, and there's not much we can do about that.

**Comment by abhi021** [comment] 2021-03-31 01:54
Can I download the dependencies manually and provide it to buf.

**Comment by bufdev** [comment] 2021-03-31 01:56
No, but even if you could, you would have to download them from buf.build since that is where these dependencies live, so I don’t think that would help.

**Comment by bufdev** [comment] 2021-04-01 14:41
Closing as I don't think there is anything actionable here.

**Comment by johanbrandhorst** [comment] 2021-05-11 13:01
Hi, what does your `buf.yaml` look like? This could laos happen if one of your dependencies is on a server that isn't reachable.

**Comment by absoludity** [comment] 2021-05-11 22:26
Doesn't seem to have anything on another server:
```
version: v1beta1
name: "buf.build/kubeapps/kubeapps"
build:
  roots:
    - .
lint:
  use:
    - DEFAULT
  except:
    - RPC_REQUEST_RESPONSE_UNIQUE
deps:
  - buf.build/beta/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
```

**Comment by johanbrandhorst** [comment] 2021-05-11 23:08
What does your lock file look like? It looks like everything is working correctly with the exception of the connection to the schema registry. Can you grab a pcap of the connection attempt? Not much debugging we can do from here unfortunately.

**Comment by absoludity** [comment] 2021-05-12 05:50
Here's a small example with which I can reproduce:

[buftest.tar.gz](https://github.com/bufbuild/buf/files/6463684/buftest.tar.gz)

And here's the pcap:

[api.buf.build.pcap.gz](https://github.com/bufbuild/buf/files/6463719/api.buf.build.pcap.gz)

**Comment by ivanovaleksey** [comment] 2021-05-21 19:54
Hi, I also have a problem with `buf generate` though it is different.
```
version: v1beta1
deps:
  - buf.build/beta/googleapis
build:
  roots:
    - proto
```
```
buf generate -v
DEBUG	get_ref	{"duration": "76.955µs"}
DEBUG	get_config	{"duration": "737.623µs"}
DEBUG	get_module_config	{"duration": "953.65µs"}
DEBUG	parse	{"duration": "2.769585ms"}
DEBUG	build	{"duration": "2.903941ms"}
DEBUG	build_module	{"duration": "2.913861ms"}
proto/api.proto:5:8:proto/google/api/annotations.proto: does not exist
DEBUG	command	{"duration": "5.706418ms"}
```
```
curl -I https://api.buf.build/
HTTP/2 404
vary: Accept-Encoding
date: Fri, 21 May 2021 19:52:28 GMT
server: envoy
```
Doing everything like in [the example](https://grpc-ecosystem.github.io/grpc-gateway/docs/tutorials/adding_annotations/)

**Comment by johanbrandhorst** [comment] 2021-05-21 19:55
Hi Aleksey, your issue is different, you're using an incorrect import, it should be `google/api/annotations.proto`.

**Comment by ivanovaleksey** [comment] 2021-05-21 19:57
@johanbrandhorst this is exactly what I have in proto file
```
syntax = "proto3";

package mypackage;

import "google/api/annotations.proto";
...
```

**Comment by bufdev** [comment] 2021-05-21 19:59
Please give us exact reproduction steps and we can look into it.

**Comment by johanbrandhorst** [comment] 2021-05-21 20:00
@ivanovaleksey Have you run `buf beta mod init` to download the dependencies? It's a manual step right now but we want to make it automatic in the future.

**Comment by ivanovaleksey** [comment] 2021-05-21 20:04
@johanbrandhorst thanks, that helps!
Sorry, I didn't about about it. This is my first time using `buf`

**Closed** 2021-05-26 17:35 UTC

**Comment by meain** [comment] 2021-12-29 04:57
I am still getting error with `buf build` and `buf mod update`.  I am hitting this issue with with both `1.0.0-rc8` and `1.0.0-rc10`.

```
$ buf build -v --debug
DEBUG   get_ref {"duration": "49.636µs"}
DEBUG   get_workspace_config    {"duration": "207µs"}
DEBUG   get_config      {"duration": "398.841µs"}
DEBUG   get_module_config       {"duration": "1.357256ms"}
DEBUG   cache_hit       {"module_pin": "buf.build/gogo/protobuf:4df00b267f944190a229ce3695781e99"}
DEBUG   cache_miss      {"module_pin": "buf.build/googleapis/googleapis:9088184d3ed04821b7e990024ff05656"}
buf: downloading buf.build/googleapis/googleapis:9088184d3ed04821b7e990024ff05656
DEBUG   grpcclient      dial    {"address": "dns:///api.buf.build"}
DEBUG   buf.alpha.registry.v1alpha1.DownloadService.Download    {"duration": "27.364µs", "Client": true, "FailFast": true}
DEBUG   command {"duration": "4.933222ms"}
Failure: the server hosted at that remote is unavailable: name resolver error: dns: A record lookup error: lookup api.buf.build: Temporary failure in name resolution


$ buf mod update -v --debug
DEBUG   get_config      {"duration": "690.719µs"}
DEBUG   grpcclient      dial    {"address": "dns:///api.buf.build"}
DEBUG   buf.alpha.registry.v1alpha1.ResolveService.GetModulePins        {"duration": "2.051260604s", "Client": true, "FailFast": true}
DEBUG   command {"duration": "2.208771943s"}
Failure: the server hosted at that remote is unavailable: error reading from server: EOF
```

Here are the `buf.yaml` and `buf.lock` files.

*buf.yaml*
```yaml
version: v1
name: buf.build/meain/usermgmt
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
  - buf.build/gogo/protobuf
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
```

*buf.lock*
```yaml
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: gogo
    repository: protobuf
    branch: main
    commit: 4df00b267f944190a229ce3695781e99
    digest: b1-sjLgsg7CzrkOrIjBDh3s-l0aMjE6oqTj85-OsoopKAw=
    create_time: 2021-08-10T00:14:28.345069Z
  - remote: buf.build
    owner: googleapis
    repository: googleapis
    branch: main
    commit: 9088184d3ed04821b7e990024ff05656
    digest: b1---R9Xre3yvH8peoJPQ0dsUYp37KzdlBlx5fjPsYekyI=
    create_time: 2021-12-23T15:04:49.66847Z
  - remote: buf.build
    owner: grpc-ecosystem
    repository: grpc-gateway
    branch: main
    commit: ff83506eb9cc4cf8972f49ce87e6ed3e
    digest: b1-iLPHgLaoeWWinMiXXqPnxqE4BThtY3eSbswVGh9GOGI=
    create_time: 2021-10-23T16:26:52.283938Z
```

Let me know if you need any more info regarding this or if I should open this up in a separate issue.

**Comment by amckinney** [comment] 2021-12-29 05:49
@meain This might be something specific to your machine. I'm able to build a module with your exact `buf.yaml` and `buf.lock` (having manually run `buf mod update` myself).

For example,
```
$ buf build --debug
DEBUG	get_ref	{"duration": "59.167µs"}
DEBUG	get_config	{"duration": "233.708µs"}
DEBUG	get_config	{"duration": "9.208µs"}
DEBUG	get_module_config	{"duration": "731.375µs"}
DEBUG	cache_miss	{"module_pin": "buf.build/gogo/protobuf:4df00b267f944190a229ce3695781e99"}
DEBUG	grpcclient	dial	{"address": "dns:///api.buf.build"}
DEBUG	buf.alpha.registry.v1alpha1.DownloadService.Download	{"duration": "555.284417ms", "Client": true, "FailFast": true}
DEBUG	buf.alpha.registry.v1alpha1.RepositoryService.GetRepositoryByFullName	{"duration": "98.6575ms", "Client": true, "FailFast": true}
DEBUG	cache_miss	{"module_pin": "buf.build/googleapis/googleapis:9088184d3ed04821b7e990024ff05656"}
DEBUG	buf.alpha.registry.v1alpha1.DownloadService.Download	{"duration": "2.363141292s", "FailFast": true, "Client": true}
DEBUG	buf.alpha.registry.v1alpha1.RepositoryService.GetRepositoryByFullName	{"duration": "93.913917ms", "Client": true, "FailFast": true}
DEBUG	cache_miss	{"module_pin": "buf.build/grpc-ecosystem/grpc-gateway:ff83506eb9cc4cf8972f49ce87e6ed3e"}
DEBUG	buf.alpha.registry.v1alpha1.DownloadService.Download	{"duration": "163.110375ms", "FailFast": true, "Client": true}
DEBUG	buf.alpha.registry.v1alpha1.RepositoryService.GetRepositoryByFullName	{"duration": "95.955542ms", "Client": true, "FailFast": true}
DEBUG	parse	{"duration": "5.746416ms"}
DEBUG	get_image	{"duration": "18.334µs"}
DEBUG	build	{"duration": "6.217833ms"}
DEBUG	build_module	{"duration": "6.250208ms"}
DEBUG	get_image_ref	{"duration": "31.583µs"}
DEBUG	put_image	{"duration": "2µs"}
DEBUG	command	{"duration": "3.688829875s"}
```

**Comment by meain** [comment] 2021-12-29 06:11
Thanks, let me see if I can figure out what might be going on. Any pointers on where I should be looking into. Could this just be a network issue?

**Comment by SGA-Tetsuri-Moriya** [comment] 2022-03-08 10:03
I am getting same error. output of `buf generate --path $API_PATH --timeout 10m -v --debug` is bellow. My colleague succeeded to execute. So my network problem. but what problem? 

```
DEBUG   get_ref {"duration": "47.706µs"}
DEBUG   get_config      {"duration": "631.117µs"}
DEBUG   get_config      {"duration": "156.823µs"}
DEBUG   get_config      {"duration": "10.593µs"}
DEBUG   get_module_config       {"duration": "800.956µs"}
DEBUG   cache_miss      {"module_pin": "buf.build/googleapis/googleapis:b66d86097dde451b8f9e39add0fa39a4"}
buf: downloading buf.build/googleapis/googleapis:b66d86097dde451b8f9e39add0fa39a4
DEBUG   grpcclient      dial    {"address": "dns:///api.buf.build"}
DEBUG   buf.alpha.registry.v1alpha1.DownloadService.Download    {"duration": "3m8.723090464s", "FailFast": true, "Client": true}
DEBUG   command {"duration": "3m8.916028561s"}
Failure: the server hosted at that remote is unavailable: error reading from server: unexpected EOF
```

**Comment by indrasaputra** [comment] 2022-03-08 10:18
I am getting the same error.

buf.yaml
```yaml
version: v1
name: buf.build/indrasaputra/arjuna-user
breaking:
  use:
    - FILE
lint:
  use:
    - BASIC
deps:
  - buf.build/googleapis/googleapis:b66d86097dde451b8f9e39add0fa39a4
  - buf.build/grpc-ecosystem/grpc-gateway:ff83506eb9cc4cf8972f49ce87e6ed3e
```

buf.lock
```yaml
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: googleapis
    repository: googleapis
    commit: b66d86097dde451b8f9e39add0fa39a4
  - remote: buf.build
    owner: grpc-ecosystem
    repository: grpc-gateway
    commit: ff83506eb9cc4cf8972f49ce87e6ed3e
```

running command: `buf build -v --debug --timeout 10m`

result 1:
```sh
DEBUG   get_ref {"duration": "48.458µs"}
DEBUG   get_workspace_config    {"duration": "161.583µs"}
DEBUG   get_config      {"duration": "159.958µs"}
DEBUG   get_config      {"duration": "4.292µs"}
DEBUG   get_module_config       {"duration": "868.875µs"}
DEBUG   cache_miss      {"module_pin": "buf.build/googleapis/googleapis:b66d86097dde451b8f9e39add0fa39a4"}
buf: downloading buf.build/googleapis/googleapis:b66d86097dde451b8f9e39add0fa39a4
DEBUG   grpcclient      dial    {"address": "dns:///api.buf.build"}
DEBUG   buf.alpha.registry.v1alpha1.DownloadService.Download    {"duration": "3m9.783458167s", "FailFast": true, "Client": true}
DEBUG   command {"duration": "3m9.846501792s"}
Failure: unexpected EOF
```

result 2:
```sh
DEBUG   get_ref {"duration": "51.5µs"}
DEBUG   get_workspace_config    {"duration": "141.75µs"}
DEBUG   get_config      {"duration": "146.291µs"}
DEBUG   get_config      {"duration": "3.667µs"}
DEBUG   get_module_config       {"duration": "781.708µs"}
DEBUG   cache_miss      {"module_pin": "buf.build/googleapis/googleapis:b66d86097dde451b8f9e39add0fa39a4"}
buf: downloading buf.build/googleapis/googleapis:b66d86097dde451b8f9e39add0fa39a4
DEBUG   grpcclient      dial    {"address": "dns:///api.buf.build"}
DEBUG   buf.alpha.registry.v1alpha1.DownloadService.Download    {"duration": "3m10.705845542s", "Client": true, "FailFast": true}
DEBUG   command {"duration": "3m10.776471917s"}
Failure: the server hosted at that remote is unavailable: error reading from server: read tcp 10.10.1.38:49837->35.193.118.40:443: read: connection reset by peer
```

this thread said that problem is probably in the network, but what specific problem it is?

**Comment by mi1wei** [comment] 2022-05-18 13:40
I am getting the same error. 

Failure: the server hosted at that remote is unavailable: error reading from server: read tcp 192.168.1.5:56924->35.193.118.40:443: use of closed network connection

**Comment by meain** [comment] 2022-08-19 09:36
Recently I started getting just error  `Failure: the server hosted at that remote is unavailable.` Just that, nothing else. But the error that was happening [here](https://github.com/bufbuild/buf/blob/089c1b8824d4d56081c5cdfb19b3a2d0335d4141/private/buf/bufcli/errors.go#L170) was:

```
unavailable: net/http: invalid header field value "Bearer \x1b[D8f71...934c95" for key Authorization
```

I deleted `~/.netrc` which was generated by an old version and it now seems to work.

**Comment by mfridman** [comment] 2022-08-19 13:39
Hey @meain, the "invalid header field" error can happen if the token is malformed, e.g., there is leading or trailing whitespace. Is it possible you were on a pre v1 buf cli?

Either way, try upgrading to the latest version of the buf cli (`v1.7.0` at the time of this writing) and if you encounter further issues let us know.

**Comment by meain** [comment] 2022-08-19 14:06
It is possible that the .netrc file was generated using an old version, but all seems to be good now. Just thought I would drop in here in case someone else runs into this.

**Comment by mfridman** [comment] 2022-08-19 14:16
Yes, very well could be. https://github.com/bufbuild/buf/pull/647

We've addresses many issues pre-v1. So the best thing for the next person is to download the latest version of `buf`, see if the issue persists with updated version, and file a new issue.
