### ISSUE TITLE
buf format does not run on Windows

### ISSUE THREAD

**Issue by jlumsden-mts** [bufbuild/buf#3505] opened 2024-12-02 08:31 UTC
### GitHub repository with your minimal reproducible example (do not leave this field blank or fill out this field with "github.com/bufbuild/buf" or we will automatically close your issue, see the instructions above!)

github.com/bufbuild/buf

### Commands

```shell
buf format
```

### Output

```shell
Failure: exec: "diff": executable file not found in %PATH%
```

### Expected Output

Works as usual, still gives the same error even without the -d flag

### Anything else?

Running v1.47.2 x86_64 on Windows 11.

It looks like it assumes "diff" is available on Windows which isn't guaranteed as it's a Unix utility. Closest Windows equivalent would be "fc" for file compare.

**Comment by doriable** [comment] 2024-12-02 17:13
Hello, this is a duplicate of this issue: https://github.com/bufbuild/buf/issues/1251.
There are a couple of workarounds provided, `diff` is available as an alias through the Powershell environment.

**Closed by doriable** 2024-12-02 17:13 UTC
Labels: Bug

**Comment by jlumsden-mts** [comment] 2024-12-03 01:50
Thanks @doriable for pointing out the workaround, I did search for this in issues prior to raising it but must have missed that one.

I would suggest though that's it's worth, at a minimum, updating the official documentation to point at that workaround *or* better yet look at fixing it so the workaround isn't required.

**Comment by doriable** [comment] 2024-12-03 16:32
This is an excellent suggestion! I'll pass that along to the documentation folks and we'll put something in :)
