### ISSUE TITLE
[BUG] `--version` outputs to `stderr`

### ISSUE THREAD

**Issue by jun-sheaf** [bufbuild/buf#258] opened 2021-02-05 01:46 UTC
## Problem

As the title says, `--version` outputs to `stderr` when it should go to `stdout`.

## Proof

Check our CI [`Validate 'setup-but'`](https://github.com/mu-io/setup-buf/actions?query=workflow%3A%22Validate+%27setup-buf%27%22).

**Comment by bufdev** [comment] 2021-02-05 01:48
Duplicate of https://github.com/bufbuild/buf/issues/135 - this is working as intended, see the comments on that issue

**Closed by bufdev** 2021-02-05 01:48 UTC

**Comment by bufdev** [comment] 2021-09-15 16:43
We've moved `--version` to stdout for v1, as an FYI!
