### ISSUE TITLE
PACKAGE_SERVICE_NO_DELETE breaking change rule does not work

### ISSUE THREAD

**Issue by sarahegler** [bufbuild/buf#1102] opened 2022-05-02 22:20 UTC
When deleting the only service from a package and running breaking change detection using the `PACKAGE` rules, no breaking changes are detected as expected. This should result in: `[filename:line]:Previously present service [service_name] was deleted from package [package_name].`

Breaking changes are detected when _renaming_ the service with `PACKAGE` rules, but missed when the service is deleted altogether. This is not an issue under `FILE` rules; both deleting and renaming the service are detected with `FILE` rules.

Took a quick look and this appears to be because the `packageToNameToService` map made [here](https://github.com/bufbuild/buf/blob/847d45959ff3d442e99bcc25f02042cdf6a52de2/private/pkg/protosource/protosource.go#L827) is empty when there is no service in a particular package. So on the branch being tested this map is empty, which means the check [here](https://github.com/bufbuild/buf/blob/v0.53.0/internal/buf/bufcheck/bufbreaking/internal/bufbreakingcheck/bufbreakingcheck.go#L920) in checkPackageServiceNoDelete is false and so we don't end up checking whether the service exists in the package.

**Comment by doriable** [comment] 2022-05-04 00:05
Thank you for reporting this issue and the very clear diagnosis! I was definitely able to reproduce this and I've put out a fix for review.

**Comment by sarahegler** [comment] 2022-05-04 00:27
thanks for jumping on this so quickly @doriable!

**Comment by bufdev** [comment] 2022-05-05 18:42
I think this is fixed now right?

**Comment by doriable** [comment] 2022-05-05 21:39
Yes, in that it's merged -- I originally intended on closing this on release, but closing now also works :)

**Closed by doriable** 2022-05-05 21:39 UTC
Labels: Bug
