### ISSUE TITLE
Local generation command not detecting comment changes

### ISSUE THREAD

**Issue by SyrieBianco** [bufbuild/buf#1146] opened 2022-05-19 23:29 UTC
When running buf generate locally for python, it does not seem to incorporate changes to comments, whereas it does when run via the github action below:

```
 - uses: arduino/setup-protoc@v1
      - name: ensure code generation
        run: |
          buf generate

          # Check if there are unstaged files in the gen/ directory after ensuring all
          # proto generation files are up to date.
          unstaged_gen_files=$(git diff --name-only origin/main origin/${GITHUB_HEAD_REF} | grep "gen/"| xargs)
          if [[ -z $unstaged_gen_files ]];
          then
              # echo "no unstaged files"
              exit 0
          fi

          >&2 echo "Please commit generated files along with proto changes"
          >&2 echo $unstaged_gen_files
          exit  1

        shell: bash
```

**Comment by SyrieBianco** [comment] 2022-05-19 23:31
Tracked internally in [TCN-90](https://linear.app/bufbuild/issue/TCN-90)

**Comment by parkwherever** [comment] 2022-05-20 00:51
I root caused the issue

Buf depends on protoc as a separate install. The protoc version that I was pulling in with the github action is ahead of the latest protoc version available on homebrew where I initially ran `buf generate` - resulting in this change between versions in differences between the python generated code. 

Would be nice not to have to manage both `buf` and `protoc` versions independently

**Comment by parkwherever** [comment] 2022-05-20 22:04
Would it be possible to specify the protoc version in buf.gen.yaml and let
buf handle the management?

**Comment by bufdev** [comment] 2022-05-26 15:25
I don't think there's a bug here, so going to close this for now.

**Closed by bufdev** 2022-05-26 15:25 UTC
